// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD_ewrAUugm0PSXmHoRpXSicwmY38JJ60',
    appId: '1:654819204507:web:d09d752a06bd4f18d6953e',
    messagingSenderId: '654819204507',
    projectId: 'tp3garagemanager',
    authDomain: 'tp3garagemanager.firebaseapp.com',
    storageBucket: 'tp3garagemanager.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU7QFkCR9dVKkKtdbSctAWJfcxjkIil6U',
    appId: '1:654819204507:android:87b25f32dd9b0185d6953e',
    messagingSenderId: '654819204507',
    projectId: 'tp3garagemanager',
    storageBucket: 'tp3garagemanager.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7lnIOqK1mqs946IWlKtbSnMnGbBvzelQ',
    appId: '1:654819204507:ios:8e572e7c3de682add6953e',
    messagingSenderId: '654819204507',
    projectId: 'tp3garagemanager',
    storageBucket: 'tp3garagemanager.firebasestorage.app',
    iosBundleId: 'com.example.tp3V2',
  );
}
